# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


stages:
- stage:  Build
  jobs:
  - job: Firstjob
    steps:
    - script: echo Hello, world ANJALI--job1!
      displayName: 'Run a one-line script'

    - script: |
        echo Add other tasks to build, test, and deploy your project.
        echo See https://aka.ms/yaml
      displayName: 'Run a multi-line script'
  - job: Secondjob
    dependsOn: Firstjob
    steps:
    - script: echo Hello, world ANJALI--job2!
      displayName: 'Run a one-line script'
  - job: Thirdjob
    dependsOn: Secondjob
    steps:
    - script: echo Hello, world ANJALI--job3!
      displayName: 'Run a one-line script'

- stage:  Deploy
  jobs:
  - job: Firstjob
    steps:
    - script: echo Hello, world ANJALI--QADeploy!
      displayName: 'Run a one-line script'
- stage:  ProdDeploy
  jobs:
  - job: Firstjob
    steps:
    - script: echo Hello, world ANJALI--ProdDeploy!
      displayName: 'Run a one-line script'


      